(********************************************************************
 * COPYRIGHT --  Sascha Geiﬂer  --  Kropf Solutions
 ********************************************************************
 * Programm: zaehler
 * Datei: calcMP.st
 * Autor: Sascha Geiﬂer
 * Erstellt: 30. M‰rz 2015
 ********************************************************************
 * Berechnung Wirkleistung
 ********************************************************************) 

FUNCTION calcMP
	calcMP:=Wirkarbeit*60;
END_FUNCTION